language: php

php: 5.3

before_script:
  - cd src 
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - phpunit --coverage-clover clover.xml

after_script:
  - php vendor/bin/coveralls -v
