<form id="project" class="usvn_form" method="post" action="<?php echo $this->url; ?>">
	<div>
		<label>
			<?php echo T_("Name"); ?><span class="usvn_require">*</span>:<br/>
			<?php echo '', $this->formText('projects_name', $this->project->name,
			($this->action != 'edit' && $this->action != 'update' ?
			array('maxlength' => 255) :
			array('maxlength' => 255, 'readonly' => 'true'))); ?>
		</label>
		<br />
		<label><?php echo T_("Description"); ?>:<br />
			<?php echo $this->formTextarea('projects_description',$this->project->description, array('rows' => 8, 'cols' => 35)); ?>
		</label>
		<br />
		<?php
			if ($this->action == 'new' || $this->action == 'create')
			{
				if( $this->template_list !== NULL )
				{
					echo '<label for="prj_template">' . T_('Project template: ') . '</label>'. $this->formSelect( 'prj_template', NULL, NULL, $this->template_list ) . "<br/>";
				}
				echo '<label for="admin">' . T_('Add me as admin of the project: ') . '</label>'. $this->formCheckbox('admin', 1,  array('checked' => true)) . "<br/>";
				if( $this->template_list === NULL )
				{
					echo '<label for="creategroup">' . T_('Create group for project: ') . '</label>'. $this->formCheckbox('creategroup', 1,  array('checked' => true)) . "<br/>";
					echo '<label for="addmetogroup">' . T_('Add me to project group: ') . '</label>'. $this->formCheckbox('addmetogroup', 1,  array('checked' => true)) . "<br/>";
					echo '<label for="createsvndir">' . T_('Create SVN standard directories (/trunk, /branches and /tags): ') . '</label>'. $this->formCheckbox('createsvndir', 1,  array('checked' => true)) . "<br/>";
				}
				else
				{
					echo '<label for="group_admin">' . T_('Add me as admin of the created project groups: ') . '</label>'. $this->formCheckbox('group_admin', 1,  array('checked' => true)) . "<br/>";
				}
			}
			else if ($this->action == 'edit')
			{
				if ($this->AdminProject != 1)
					echo '<label>' . T_('Add me as admin of the project:') . '<input type = "checkbox" name="admin" value="admin">';
				else
					echo '<label>' . T_('Add me as admin of the project:') . '<input type = "checkbox" name="admin" value="admin" checked >';
			}
		?>
		<?php if (isset($this->group)) echo $this->formHidden('groups_id', $this->group->id); ?>
		<br/>
		<?php echo $this->formSubmit('submit', T_("Submit"), array("onclick" => 'return checkName();')); ?>
		<br />
	</div>
</form>
